### PR TITLE
Fix image caption

### PR DESCRIPTION
**Pull request by mankoff**
+ Clarify that this tutorial step is displaying results from future tutorial steps
+ Fix image caption. Middle is 10 km run, Right  is 20 km run.

### CODE REVIEW

**Comment by ckhroulev** [comment]
@mankoff Thank you for the clarification! I really appreciate all contributions, no matter how small.

Changes like this should be applied to the `dev` branch instead of `main`. Please make sure to [allow edits by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so that I can rebase your commit to `dev` and merge this PR. (I'm not sure if you did this already, but right now I cannot push to <https://github.com/NASA-GISS/pism/tree/mankoff-doc>. Thanks!)

**Comment by mankoff** [comment]
Hm. I read https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork but cannot figure out how to give you commit access to my branch. I suggest closing this, and I'll issue a new PR from my `dev` branch to your `dev` branch ?

**Comment by ckhroulev** [comment]
Since this is just one commit I can easily cherry-pick without any loss of information (authorship, etc). So -- don't worry about it.

Thanks again!

**Comment by ckhroulev** [comment]
@mankoff Please see <https://github.com/pism/pism/commit/2c8dfdd4c8b6ac6b51ef995c8cb12b5315478238>. I will make sure this change is included in all future releases.

**Pull request closed without merging**
