### PR TITLE
Add contributing guidelines

### PR DESCRIPTION
**Pull request by ckhroulev**
This is intended to replace #430 (I needed to update relevant parts of the manual in addition to adding `CONTRIBUTING.rst`).

So, since I'm telling people to open pull requests, here's one. Comments, edits, etc are welcome.

@aaschwanden, @bueler: What do you think? What did I miss? What should be different?

### CODE REVIEW

**Comment by ckhroulev** [comment]
I need to add detailed instructions with corresponding Git commands (see #209). Once that is done I will close #209.

**Comment by bueler** [comment]
Awesome.  Let me know when I should pull which page/tab at pism-docs.org and I will do that work.

**Comment by ckhroulev** [comment]
- We need to mention that we use CircleCI to run automatic test and that all tests should pass.
- Fixing test failures on CircleCI is much easier if you can run them locally, so I need to describe how to do that.

**Comment by anders-dc** [comment]
> * Fixing test failures on CircleCI is much easier if you can run them locally, so I need to describe how to do that.

The CircleCI containerized tests can be run locally[[0](https://circleci.com/docs/2.0/local-cli/),[1](https://circleci.com/docs/2.0/local-cli/#run-a-job-in-a-container-on-your-machine)]. Maybe this is worth mentioning explicitly, or at least linking to the docs?

**Comment by ckhroulev** [comment]
@anders-dc Yes, I've been using `circleci local execute` myself and that's exactly what I was referring to (i.e. I'm going to document that, at least briefly).

**Comment by sebhinck** [comment]
@ckhroulev  Thank you a lot for implementing the fixes. It seems like you added a lot of effort to rework this whole part of the code. Also from the next release on the elastic part will be enabled by default, isn't it? I think that's a good decision.

Regarding #443

Maybe this fits into *Editing source code*: The tool KDev helped me a lot to unravel all the layers of C++ classes, and to finally find where a specific function was explicitly defined. I am sure there are many similar tools that do the same (maybe also EMACS?!).

**Comment by ckhroulev** [comment]
@sebhinck:

- Regarding the elastic part of the LC model (#435): quite frequently the hard part of fixing a bug is making sure that a) it is fixed and b) it stays fixed. That's what most of that effort went into.

  Also, now that I've thought about it I can tell that porting fixes to earlier PISM versions would require more time than I can afford to spend on it. Here the problem is that that #424 is related to other bugs in the LC model (#370, #377, #422) and just fixing #435 is not enough: one might as well replace the old implementation of the LC model with the one from the `dev` branch.

  And yes, in future versions the elastic part of the LC model will be "on" by default (see 344de5f959eb425b1e4cdca1219cbeb96a03474f and a5017cc05279b7c506b1cc1bd3df19e6fb286030).
- Regarding KDev: would you mind submitting a pull request with the appropriate edits?

**Comment by sebhinck** [comment]
Just realized that my post ended up in the wrong issue, sorry!

@ckhroulev 
- Ok, I see the problem with the LC is even more complex. I thought that my few commits would solve that issue and would be simple to also merge into older releases. 
Would you consider the other issues, you have mentioned above, as fixed with your changes or is more testing needed?

- KDev: ok, I will prepare something.

**Pull request merged**
