### PR TITLE
Add continuous integration

### PR DESCRIPTION
**Pull request by anders-dc**
This pull request adds continuous integration to **pism:dev** using [CircleCI](https://circleci.com), which builds PISM and runs `make test` for *every commit and pull request* submitted to the **dev** branch of this repository. The continued testing makes it easy to identify if a commit or pull request breaks or fixes any of the tested functionality. Every run takes place in a clean Debian Stable environment, packaged as a [custom docker image](https://github.com/anders-dc/pism-docker). As a sidenote, the Debian image is constructed from the instructions given in the [PISM documentation](https://pism-docs.org/sphinx/installation/prerequisites.html) (with exception of PETSc).

## Actions required
CircleCI needs access to the Github repository to continuously monitor commits and pull requests, and report their results. A person with administrative credentials to [github.com/pism](https://github.com/pism) needs to sign in to [circleci.org](https://circleci.com), and accept the Github access permissions confirmation. You may want to disable e-mail notifications from *User Settings*.

### CODE REVIEW

**Comment by anders-dc** [comment]
See [here](https://circleci.com/gh/anders-dc/pism/26) for example output.

**Comment by ckhroulev** [comment]
(Copied from #439.)

Thanks for working on this!

Here are my comments:

- it would be great if you could build PISM with its Python bindings enabled: many regression tests use these bindings. This would require adding `petsc4py` to PISM's prerequisites and setting `-DPism_BUILD_PYTHON_BINDINGS=YES` when running CMake.
- it would also be useful to build PISM with all the optional features enabled to improve code coverage (I'm thinking about parallel NetCDF-4, PnetCDF, and PROJ).

**Comment by anders-dc** [comment]
Alright, that should be doable. Just a slight hiccup. I installed `libproj-dev`, `libnetcdf-pnetcdf-dev`, `libpnetcdf-dev`, `pnetcdf-bin`, and `python-petsc4py` from the Debian repositories. However, I encounter the following error:

```
$ cmake .. -DPism_BUILD_PYTHON_BINDINGS=Yes -DPism_USE_PROJ4=Yes -DPism_USE_PNETCDF=Yes -DPism_USE_PARALLEL_NETCDF4=Yes`
  [...]
  Selected NetCDF library (include: /usr/include, lib:
  /usr/lib/x86_64-linux-gnu/libnetcdf.so) does not support parallel I/O.
```

Do I need to install `libpnetcdf-dev` (or `libnetcdf-pnetcdf-dev`) instead of `libnetcdf-dev`?

**Comment by ckhroulev** [comment]
Hmm. I don't have access to a Debian box right now (I'll take a look at it later), but it seems to me that you need [`libnetcdf-mpi-dev`](https://packages.debian.org/buster/libnetcdf-mpi-dev) and [`libpnetcdf-dev`](https://packages.debian.org/buster/libpnetcdf-dev) for the parallel version of NetCDF-4 and PnetCDF. (Note that NetCDF-4 can also be built with PnetCDF, but that's not what we need. I suspect that this is what `libnetcdf-pnetcdf-dev` provides.)

You do need `libnetcdf-dev` no matter what.

You would also need [`python-petsc4py`](https://packages.debian.org/buster/python-petsc4py) and [`swig`](https://packages.debian.org/buster/swig) for PISM's Python bindings. These days PISM supports both Python 2.7 and Python 3.x, so it should not matter which one you use.

**Comment by anders-dc** [comment]
Thanks!

**Comment by anders-dc** [comment]
I coudln't get parallel NetCDF to work for the time being, but the Python bindings are now included in the build (see [anders-dc/pism-docker](https://github.com/anders-dc/pism-docker/blob/master/debian/Dockerfile) for updated Docker image). With the Python bindings the `make test` suite is up to 38 tests, which all pass ([build log](https://circleci.com/gh/anders-dc/pism/29)).

By default, the CI pipeline will report the success of each build next to the relevant commits in the repository commit history. A lot of projects have status badges in the readme too. Would you like for me to add one of those or not?

**Comment by ckhroulev** [comment]
@anders-dc Regarding the status badge: yes, please.

**Comment by anders-dc** [comment]
Ok, the status badge is now in the README, right below the header. The badge looks at the dev branch of this repository (pism/pism), not my own fork and branch.

**Comment by anders-dc** [comment]
Is there any interest in adopting [anders-dc/pism-docker](https://github.com/anders-dc/pism-docker) that is used for the CI instances? I am more than happy to maintain it wherever it is situated, but figure you may want to keep everything under one roof.

**Comment by ckhroulev** [comment]
> ... you may want to keep everything under one roof.

Yes, Indeed.

I will set up a similar custom Docker image and will put the `Dockerfile` in the PISM's source code tree. (So far I see no reason to keep it separate.)

Thanks for your work on this, it has been very helpful.

**Comment by anders-dc** [comment]
@ckhroulev sounds good to me.

By the way, you may want to add the following conditional to the circleci configuration to avoid running checks on **pism:master** until the CI configuration is merged into it ([source in docs](https://circleci.com/docs/2.0/configuration-reference/#branches)).

```
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 5f96562f7..34d5132c7 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,11 @@
 version: 2
 jobs:
   build:
+
+    branches:
+      ignore:
+        - master
+
     docker:
       - image: admesg/pism-debian:0.1.5
```

**Comment by ckhroulev** [comment]
@anders-dc Thanks! I switched to my own version of the image. I had to build HDF5 and NetCDF (with parallel I/O support) from sources, but that's OK.

Now CircleCI runs all 62 regression tests.

**Comment by anders-dc** [comment]
Excellent!

**Pull request merged**
