### PR TITLE
Update IceBin Interface

### PR DESCRIPTION
**Pull request by citibeth**
These changes should not be controversial since they only affect IceBin.  I'm not sure if they compile (they were merged from the same changes on an older branch that does compile).  But since they only affect IceBin, I'm find if they don't build for a while; I will eventually update.

### CODE REVIEW

**Comment by ckhroulev** [comment]
Hmm. This is strange. All the changes to `src/icebin/IBIceModel.cc` seem counter-productive, i.e. if I merge this into `dev` I will go from having code that compiles and is up-to-date with the current `dev` branch to code that is broken and does not compile.

(I have `Pism_BUILD_ICEBIN` set to `ON` on the computer I use for development, so I have been updating `src/icebin/IBIceModel.cc` along with the rest of PISM.)

**Comment by citibeth** [comment]
OK... let's just leave the PR as-is until I can get to it.  Thanks!

**Comment by ckhroulev** [comment]
Sounds good.

PS: I cherry-picked the first commit (Updates to comments) -- this is definitely not controversial and will not break anything. And that way we don't need to remember to include this change later.

**Comment by ckhroulev** [comment]
Sadly at 4 years old this PR is too stale to invest time in.

**Pull request closed without merging**
